name: blaise_wallet_flutter
description: A new Flutter project.

version: 1.1.3+24

environment:
  sdk: ">=2.11.99 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # PascalCoin signing/rpc/etc.
  pascaldart: ^2.0.0

  # Localization
  intl: ^0.17.0

  # AutoSizeText widget
  auto_size_text: ^2.1.0

  # Flare for animations
  flare_flutter: ^2.0.6

  # SVG
  flutter_svg: ^0.22.0

  # Font awesome
  font_awesome_flutter: ^8.8.1

  # Share files
  share:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/share
      ref: master
  
  # Slidable
  flutter_slidable: ^0.5.7

  # QR Code Generator
  qr_flutter: ^3.0.1

  # Banner style alerts
  oktoast: ^3.0.0

  # Service locator
  get_it: ^6.0.0

  # To avoid keyboard overlap
  keyboard_avoider: ^0.1.2

  # KeyStore/keychain
  flutter_secure_storage: ^5.0.2

  # shared prefs
  shared_preferences: ^2.0.8

  # Biometrics
  local_auth: ^1.0.0-nullsafety.3

  # mobx for state
  mobx: ^2.0.0-nullsafety.3
  flutter_mobx: ^2.0.0-nullsafety.0

  # Nicer logging
  logger: ^1.0.0

  # quiver - various Dart utilities
  quiver: ^3.0.1+1

  # big decimal
  decimal: ^1.3.0

  # Event Bus
  event_taxi: ^1.0.0

  # Vibrate
  vibrate:
    git:
      url: https://github.com/bbedward/flutter_vibrate.git
      ref: master

  # Device-specific info
  device_info: ^2.0.3

  # App build info
  package_info: ^2.0.2

  # Serialization
  json_annotation: ^4.3.0

  # SQLite
  sqflite: ^2.0.0+4

  # OS Path Info
  path_provider: ^2.0.1

  # Native file chooser
  file_picker: ^3.0.0-nullsafety.0

  # Various string validations
  validators: 2.0.0

  # Webview
  flutter_webview_plugin: ^0.4.0

  # QR scanning
  barcode_scan:
    git:
      url: https://github.com/bbedward/flutter_barcode_reader.git
      ref: master

  # Push notifications
  firebase_messaging: ^11.1.0
  firebase_core: ^1.10.0

dependency_overrides:
  analyzer: ^2.7.0
  dart_style: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  mobx_codegen: ^2.0.0-nullsafety.1
  json_serializable: ^6.0.1
  intl_translation:
    git:
      url: https://github.com/bbedward/intl_translation.git
      ref: master

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Metropolis
      fonts:
        - asset: fonts/Metropolis-Black.ttf
          weight: 900
        - asset: fonts/Metropolis-ExtraBold.ttf
          weight: 800
        - asset: fonts/Metropolis-Bold.ttf
          weight: 700
        - asset: fonts/Metropolis-SemiBold.ttf
          weight: 600
        - asset: fonts/Metropolis-Medium.ttf
          weight: 500
        - asset: fonts/Metropolis-Regular.ttf
          weight: 400
        - asset: fonts/Metropolis-Light.ttf
          weight: 300
        - asset: fonts/Metropolis-ExtraLight.ttf
          weight: 200
        - asset: fonts/Metropolis-Thin.ttf
          weight: 100
    - family: RobotoRegular
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Black.ttf
          weight: 900
        - asset: fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: fonts/SourceCodePro-Semibold.ttf
          weight: 600
        - asset: fonts/SourceCodePro-Medium.ttf
          weight: 500
        - asset: fonts/SourceCodePro-Regular.ttf
          weight: 400
        - asset: fonts/SourceCodePro-Light.ttf
          weight: 300
        - asset: fonts/SourceCodePro-ExtraLight.ttf
          weight: 200
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 600
  assets:
    - assets/animation_welcome.flr
    - assets/animation_welcome_copper.flr
    - assets/animation_welcome_dark.flr
    - assets/animation_send.flr
    - assets/animation_send_copper.flr
    - assets/animation_send_dark.flr
    - assets/animation_name_change.flr
    - assets/animation_name_change_copper.flr
    - assets/animation_name_change_dark.flr
    - assets/animation_sale.flr
    - assets/animation_sale_copper.flr
    - assets/animation_sale_dark.flr
    - assets/animation_transfer.flr
    - assets/animation_transfer_copper.flr
    - assets/animation_transfer_dark.flr
    - assets/animation_get_account.flr
    - assets/animation_get_account_copper.flr
    - assets/animation_get_account_dark.flr
    - assets/animation_search.flr
    - assets/illustration_backup.svg
    - assets/illustration_new_wallet.svg
    - assets/illustration_two_options.svg
    - assets/illustration_borrowed.svg
    - assets/illustration_security.svg
    - assets/illustration_backup_dark.svg
    - assets/illustration_new_wallet_dark.svg
    - assets/illustration_two_options_dark.svg
    - assets/illustration_borrowed_dark.svg
    - assets/illustration_security_dark.svg
    - assets/illustration_backup_copper.svg
    - assets/illustration_new_wallet_copper.svg
    - assets/illustration_two_options_copper.svg
    - assets/illustration_borrowed_copper.svg
    - assets/illustration_security_copper.svg
    - assets/country_phone_map.json

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
