# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

def ensure_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
  create_keychain(
    name: name,
    password: 'blaisetempkeychainpassword',
    unlock: true,
    timeout: false
  )
end

platform :ios do
  desc "Build & sign iOS app"
  lane :build_ios do |options|
    ensure_temp_keychain 'fastlane_blaise'
    match(
      type: "appstore",
      readonly: is_ci,
      keychain_name: 'fastlane_blaise'
    )
    sh "./flutter_test.sh"
    sh "./flutter_build.sh --clean"
    build_ios_app(
      export_options: {
        method: "app-store"
      },
    )
    delete_keychain(
      name: 'fastlane_blaise'
    ) if File.exist? File.expand_path("~/Library/Keychains/fastlane_blaise-db")
  end

  desc "Upload iOS app to app store"
  lane :deploy_ios do |options|
    if options[:testflight]
      upload_to_testflight(
        skip_submission: true,
        ipa: "./Runner.ipa"
      )
    else
      deliver(
        skip_metadata: false,
        skip_screenshots: true,
        submit_for_review: true,
        force: true,
        ipa: "./Runner.ipa"
      )
    end
  end
end
