name: DEPLOY_RELEASE

on:
  push:
    tags:
    - 'v*-release-android'

jobs:
  run_tests:
    name: Run tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master   

      - name: Run tests
        run: |
          flutter pub get
          flutter test

  build_android:
    name: Build android app
    needs: run_tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - name: Build artifacts
        working-directory: android
        env:
          FLUTTER_PATH: /Users/adapps/flutter
          ANDROID_SDK_PATH: /Users/adapps/Library/Android/Sdk
          GEM_HOME: ~/.gems
        run: |
          echo flutter.sdk=${{ env.FLUTTER_PATH }} > local.properties
          echo sdk.dir=${{ env.ANDROID_SDK_PATH }} >> local.properties
          echo flutter.buildMode=release >> local.properties
          echo storeFile=${{ secrets.ANDROID_KEYSTORE_PATH }} > key.properties
          echo keyAlias=${{ secrets.ANDROID_KEY_ALIAS }} >> key.properties
          echo keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }} >> key.properties
          echo storePassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }} >> key.properties
          /usr/local/bin/fastlane build_android production:true
          rm -f key.properties

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: android-apk
          path: build/app/outputs/apk/release/app-release.apk

      - name: Upload Bundle
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab

  deploy_android:
    name: Deploy android production
    needs: build_android
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master   
      - name: Download AAB
        uses: actions/download-artifact@v2
        with:
          name: android-aab

      - name: Set workspace in env
        run: echo "workspace=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Deploy android
        if: success()
        working-directory: android
        env:
          AAB_PATH: ${{ env.workspace }}/app-release.aab
          GEM_HOME: ~/.gems
        run: |
          /usr/local/bin/fastlane deploy_android production:true